A fix.

diff --git a/build-rpm b/build-rpm
--- a/build-rpm
+++ b/build-rpm
@@ -36,7 +36,6 @@ while [ x$1 != "x" ] ; do \
 done \
 ) | sort -u`
 if [ "${DISTRIBUTIONS}" == "" ] ; then
-   sudo docker exec -t ubuntu-test bash -c "cat /etc/fedora-release"
    release=`cat /etc/fedora-release | sed -e "s/^\(.*\) release \([0-9]*\) (\(.*\))$/\2/g"`
    arch=`uname -m`
 
@@ -52,10 +51,13 @@ echo -e "\x1b[34mPACKAGE_VERSION:   ${PACKAGE_VERSION}\x1b[0m"
 echo -e "\x1b[34m###########################################\x1b[0m"
 
 
-# ====== Find source RPM ====================================================
+# ====== Create source RPM ==================================================
+./make-srpm
+
+echo find $HOME/rpmbuild/SRPMS/ -name "${PACKAGE}-*${PACKAGE_VERSION}*-*.src.rpm"
 PACKAGE_SRPM=`find $HOME/rpmbuild/SRPMS/ -name "${PACKAGE}-*${PACKAGE_VERSION}*-*.src.rpm"`
 if [ ! -e "${PACKAGE_SRPM}" ] ; then
-   echo >&2 "ERROR: Cannot find SRPM ${PACKAGE_SRPM} in $HOME/rpmbuild/SRPMS!"
+   echo >&2 "ERROR: Cannot find SRPM ${PACKAGE}-*${PACKAGE_VERSION}*-*.src.rpm in $HOME/rpmbuild/SRPMS!"
    exit 1
 fi
 
@@ -80,9 +82,9 @@ for DISTRIBUTION in ${DISTRIBUTIONS} ; do
    # Build the binary RPM
    # NOTE: using old chroot instead of container, to allow running it inside a container!
    mock -r ${DISTRIBUTION} --old-chroot --init
-   mock -r ${DISTRIBUTION} --old-chroot --installdeps ${PACKAGE}_SRPM
+   mock -r ${DISTRIBUTION} --old-chroot --installdeps ${PACKAGE_SRPM}
    mock -r ${DISTRIBUTION} --old-chroot --install openssl pesign
-   mock -r ${DISTRIBUTION} --old-chroot --no-clean --rebuild ${PACKAGE}_SRPM
+   mock -r ${DISTRIBUTION} --old-chroot --no-clean --rebuild ${PACKAGE_SRPM}
 
    # Check whether files are at the right location
    PACKAGE_RPMS=`find /var/lib/mock/${distribution}/result -name "${PACKAGE}-*${PACKAGE_VERSION}*-*.rpm" | grep -v "${PACKAGE}-*${PACKAGE_VERSION}*-*.src.rpm" || true`
