Fixed pkg-plist handling.
git-svn-id: https://svn.tdr.iem.uni-due.de:8443/svn/sctp-misc/trunk/netperfmeter@993 acdd8558-d4fd-0310-b0a5-8cf3c1ec824a

diff --git a/freebsd/netperfmeter/make-diff b/freebsd/netperfmeter/make-diff
--- a/freebsd/netperfmeter/make-diff
+++ b/freebsd/netperfmeter/make-diff
@@ -40,8 +40,10 @@ for file in $PACKAGING_FILES ; do
    if [ -e /usr/ports/$CATEGORY/$PACKAGE/$file -a -e $file ] ; then
       diff -uN /usr/ports/$CATEGORY/$PACKAGE/$file $file >>$PACKAGE.diff
    else
-      echo >&2 "ERROR: Unable to compare /usr/ports/$CATEGORY/$PACKAGE/$file and $file"
-      exit 1
+      if [ -e /usr/ports/$CATEGORY/$PACKAGE/$file ] ; then
+         echo >&2 "ERROR: Unable to compare /usr/ports/$CATEGORY/$PACKAGE/$file and $file"
+         exit 1
+      fi
    fi
 done
 
