Kernel test script added.
git-svn-id: https://svn.tdr.iem.uni-due.de:8443/svn/sctp-misc/trunk/netperfmeter@883 acdd8558-d4fd-0310-b0a5-8cf3c1ec824a

diff --git a/src/archive-measurement b/src/archive-measurement
--- a/src/archive-measurement
+++ b/src/archive-measurement
@@ -21,16 +21,16 @@
 #
 
 if [ ! -e run-$1 ] ; then
-   echo "ERROR: run-$1 does not exist!"
-   exit
+   echo 2>&1 "ERROR: run-$1 does not exist!"
+   exit 1
 fi
 if [ ! -e plot-$1.R ] ; then
-   echo "ERROR: plot-$1.R does not exist!"
-   exit
+   echo 2>&1 "ERROR: plot-$1.R does not exist!"
+   exit 1
 fi
 if [ ! -e $1 ] ; then
-   echo "ERROR: $1 directory does not exist!"
-   exit
+   echo 2>&1 "ERROR: $1 directory does not exist!"
+   exit 1
 fi
 
 
@@ -39,8 +39,12 @@ if [ x$DESTINATION = "x" ] ; then
    DESTINATION=.
 fi
 
+result=1
 R --vanilla <plot-$1.R && \
 echo "Step 1: Archiving results only to $DESTINATION/$1.tar.bz2 ..." && \
 tar cjf $DESTINATION/$1.tar.bz2 run-$1 plot-$1.R $1.pdf $1/Results && \
 echo "Step 2: Archiving everything to $DESTINATION/$1-complete.tar.bz2 ..." && \
-tar cjf $DESTINATION/$1-complete.tar.bz2 run-$1 plot-$1.R $1.pdf $1
+tar cjf $DESTINATION/$1-complete.tar.bz2 run-$1 plot-$1.R $1.pdf $1 && \
+result=0
+
+exit $result
