Further script clean-ups.

diff --git a/src/flowtest-many b/src/flowtest-many
--- a/src/flowtest-many
+++ b/src/flowtest-many
@@ -29,9 +29,17 @@
 # Bash options:
 set -eu
 
+
+TCP_FLOWS=5
+TCP_PARAMS="const0:const0:const0:const1460:cmt=off"
+
+UDP_FLOWS=5
+UDP_PARAMS="const0:const0:const25:const2500:onoff=+pareto0.166667,1.5,+pareto0.166667,1.5,repeat"
+
+
 # ====== Handle arguments ===================================================
-if [ $# -lt 2 ] ; then
-   echo >&2 "Usage: $0 server:port [processes]"
+if [ $# -lt 1 ] ; then
+   echo >&2 "Usage: $0 server:port [runtime]"
    exit 1
 fi
 SERVER="$(echo "$1" | sed -s 's/:.*$//g')"
@@ -40,39 +48,32 @@ if [[ ! "${PORT}" =~ ^[0-9]+$ ]] ; then
    echo >&2 "ERROR: Invalid port ${PORT}!"
    exit 1
 fi
-
-if [ "$2" != "" ] ; then
-   procs="$2"
-else
-   procs=16
+RUNTIME=10
+if [ $# -ge 2 ] ; then
+   RUNTIME="$2"
+fi
+if [[ ! "${RUNTIME}" =~ ^[0-9]+$ ]] ; then
+   echo >&2 "ERROR: Invalid runtime ${RUNTIME}!"
+   exit 1
 fi
 
-RUNTIME=5
-SLEEP=3
+make
+rm -f vgcore.* core.* core
 
-mkdir -p stresstest-output
-rm -f stresstest-output/*
-(
-n=0
-while true ; do
 
-   # ====== Test #1 =========================================================
-   n=$((n+1))
-   label="$(printf "S%08u" "${n}")"
-   echo "\
-random-sleep 0 ${SLEEP} && ./netperfmeter ${SERVER}:${PORT} \
--control-over-tcp \
--config=stresstest-output/${label}.config \
--vector=stresstest-output/${label}.vec.bz2 \
--scalar=stresstest-output/${label}.sca.bz2 \
--logfile=stresstest-output/${label}.log \
--loglevel=0 \
--udp const10:const1400:const10:const1400 \
--runtime=${RUNTIME}"
-
-# -tcp const80:const10000:const80:const10000 \
-# -sctp const20:const10000:const20:const10000 const20:const10000:const20:const10000 \
-# -dccp const80:const1400:const80:const1400 \
-
+# ====== Run NetPerfMeter ===================================================
+options=""
+i=0 ; while [ $i -lt $TCP_FLOWS ] ; do
+   options="${options} -tcp ${TCP_PARAMS}"
+   i=$((i+1))
 done
-) | parallel -j"${procs}"
+i=0 ; while [ $i -lt $UDP_FLOWS ] ; do
+   options="${options} -udp ${UDP_PARAMS}"
+   i=$((i+1))
+done
+
+echo "OPTIONS=${options}"
+# shellcheck disable=SC2086
+./netperfmeter "${SERVER}:${PORT}" \
+   ${options} \
+   -runtime="${RUNTIME}"
