Updated test scripts.

diff --git a/src/flow-test b/src/flow-test
--- a/src/flow-test
+++ b/src/flow-test
@@ -2,17 +2,30 @@
 
 set -eu
 
+# ====== Handle arguments ===================================================
+if [ $# -lt 1 ] ; then
+   echo >&2 "Usage: $0 server:port"
+   exit 1
+fi
+SERVER="$(echo "$1" | sed -s 's/:.*$//g')"
+PORT="$(echo "$1" | sed -s 's/^.*://g')"
+if [[ ! "${PORT}" =~ ^[0-9]+$ ]] ; then
+   echo >&2 "ERROR: Invalid port ${PORT}!"
+   exit 1
+fi
+
+
 make
 rm -f vgcore.* core.* core
 
-./netperfmeter localhost:9000 \
+./netperfmeter "${SERVER}:${PORT}" \
    -control-over-tcp \
    -scalar=x.sca.bz2 -vector=x.vec.bz2 \
    -udp const30:const68000:const30:const68000:maxmsgsize=1300 \
    -runtime=5
 
-# ./netperfmeter localhost:9000 \
+# ./netperfmeter "${SERVER}:${PORT}" \
 #    -control-over-tcp \
 #    -scalar=y.sca.bz2 -vector=y.vec.bz2 \
-#    -sctp const30:const6800:const30:const6800:maxmsgsize=1300 const30:const6800:const30:const6800:maxmsgsize=1300 const30:const6800:const30:const6800:maxmsgsize=1300\
+#    -sctp const30:const6800:const30:const6800:maxmsgsize=1300 const30:const6800:const30:const6800:maxmsgsize=1300 const30:const6800:const30:const6800:maxmsgsize=1300 \
 #    -runtime=5
diff --git a/src/fuzz-test b/src/fuzz-test
--- a/src/fuzz-test
+++ b/src/fuzz-test
@@ -4,10 +4,16 @@ set -eu
 
 # ====== Handle arguments ===================================================
 if [ $# -lt 2 ] ; then
-   echo >&2 "Usage: $0 netperfmeter_server [processes]"
+   echo >&2 "Usage: $0 server:port [processes]"
    exit 1
 fi
-SERVER="$1"
+SERVER="$(echo "$1" | sed -s 's/:.*$//g')"
+PORT="$(echo "$1" | sed -s 's/^.*://g')"
+if [[ ! "${PORT}" =~ ^[0-9]+$ ]] ; then
+   echo >&2 "ERROR: Invalid port ${PORT}!"
+   exit 1
+fi
+
 if [ "$2" != "" ] ; then
    procs="$2"
 else
@@ -16,10 +22,12 @@ fi
 
 
 # ====== Run fuzz-test with given number of processes =======================
-echo "Running fuzz-test with ${procs} processes ..."
+dataPort=${PORT}
+controlPort=$((PORT+1))
+echo "Running fuzz-test to ${SERVER}:${dataPort} and ${SERVER}:${controlPort} with ${procs} processes ..."
 (
    while true ; do
-      echo "cat /dev/urandom | nc "${SERVER}" 9000"
-      echo "cat /dev/urandom | nc "${SERVER}" 9001"
+      echo "cat /dev/urandom | nc ${SERVER} ${dataPort}"
+      echo "cat /dev/urandom | nc ${SERVER} ${controlPort}"
    done
 ) | parallel -j${procs} | strings
