Improved lookup of getopt command in scripts.

diff --git a/src/plot-netperfmeter-results b/src/plot-netperfmeter-results
--- a/src/plot-netperfmeter-results
+++ b/src/plot-netperfmeter-results
@@ -49,7 +49,28 @@ version () {
 # ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
-GETOPT="$(PATH=/usr/local/bin:${PATH} which getopt)"
+UNAME="$(uname)"
+case "${UNAME}" in
+   FreeBSD)
+      GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
+      ;;
+   NetBSD)
+      GETOPT="$(PATH="/usr/pkg/bin:${PATH}" command -v getopt)"
+      ;;
+   OpenBSD)
+      GETOPT="$(command -v gnugetopt)"
+      ;;
+   Darwin)
+      GETOPT="$(env PATH="/opt/homebrew/opt/gnu-getopt/bin:${PATH}" command -v getopt)"
+      ;;
+   *)
+      GETOPT="$(command -v getopt)"
+      ;;
+esac
+if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
+   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
+   exit 1
+fi
 options="$(${GETOPT} -o wkphv --long own-file,ownfile,keep-summaries,per-flow-plots,help,version -a -- "$@")"
 # shellcheck disable=SC2181
 if [[ $? -ne 0 ]]; then
