Added TD EdgeDevice QDisc sources.
git-svn-id: https://svn.tdr.iem.uni-due.de:8443/svn/sctp-misc/trunk/netperfmeter@507 acdd8558-d4fd-0310-b0a5-8cf3c1ec824a

diff --git a/src/setqos b/src/setqos
--- a/src/setqos
+++ b/src/setqos
@@ -21,7 +21,7 @@
 #
 
 if [ $# -lt 1 ] ; then
-   echo >&2 "Usage: $0 [ID] [Source Network] [Destination Network] [Bandwidth in kbit/s] [Delay in ms] [Loss]"
+   echo >&2 "Usage: $0 [ID] [Source Network] [Destination Network] [Bandwidth in kbit/s] [Delay in ms] [Loss Rate] [Error Rate]"
    exit 1
 fi
 
@@ -41,17 +41,22 @@ fi
 BANDWIDTH=""
 DELAY=""
 LOSS=""
+ERROR=""
 addRule=0
-if [ 0$4 -gt 0 ] ; then
+if [ "$4" != "" ] ; then
    BANDWIDTH="$4"
    addRule=1
 fi
-if [ 0$5 -gt 0 ] ; then
+if [  "$5" != "" ] ; then
    DELAY="$5"
    addRule=1
 fi
-if [ 0$6 -gt 0 ] ; then
+if [ "$6" != "" ] ; then
    LOSS="$6"
+   addRule=1
+fi
+if [ "$7" != "" ] ; then
+   ERROR="$7"
    addRule=1
 fi
 
@@ -75,13 +80,16 @@ if [ "$SYSTEM" = "Linux" ] ; then
          DELAY="delay ${DELAY}ms"
       fi
       if [ "$LOSS" != "" ] ; then
-         LOSS="loss ${LOSS}"
+         LOSS="loss `./ldcalc ${LOSS} "*" "100.0"`%"
+      fi
+      if [ "$ERROR" != "" ] ; then
+         ERROR="corrupt `./ldcalc ${ERROR} "*" "100.0"`%"
       fi
       for iface in $INTERFACES ; do
          echo "=== Configuring interface $iface ... ========================="
          tc qdisc add dev $iface root handle 9$ID:0 prio
-         tc qdisc add dev $iface parent 9$ID:3 handle 8$ID:0 netem $DELAY $LOSS
-         tc qdisc add dev $iface parent 8$ID:0 handle 7$ID:0 tbf $BANDWIDTH burst 16000 latency limit 150000
+         tc qdisc add dev $iface parent 9$ID:3 handle 8$ID:0 netem $DELAY $LOSS $ERROR
+         tc qdisc add dev $iface parent 8$ID:0 handle 7$ID:0 tbf $BANDWIDTH burst 16000 limit 150000
          tc filter add dev $iface protocol ip parent 9$ID:0 prio 3 u32 match ip src $NETWORK_SRC match ip dst $NETWORK_DST flowid 9$ID:3
          tc -s qdisc ls dev $iface
       done
@@ -101,8 +109,11 @@ elif [ "$SYSTEM" = "FreeBSD" ] ; then
       if [ "$LOSS" != "" ] ; then
          LOSS="plr ${LOSS}"
       fi
+      if [ "$ERROR" != "" ] ; then
+         ERROR="ber ${ERROR}"
+      fi
       ipfw add $ID pipe $ID out src-ip $NETWORK_SRC dst-ip $NETWORK_DST
-      ipfw pipe $ID config $BANDWIDTH $DELAY $LOSS queue 100
+      ipfw pipe $ID config $BANDWIDTH $DELAY $LOSS $ERROR queue 100
    fi
 
 
