setqos: - Improved error handling. - Linux configuration should now be useful. Needs testing in real network.
git-svn-id: https://svn.tdr.iem.uni-due.de:8443/svn/sctp-misc/trunk/netperfmeter@801 acdd8558-d4fd-0310-b0a5-8cf3c1ec824a

diff --git a/src/setqos b/src/setqos
--- a/src/setqos
+++ b/src/setqos
@@ -66,42 +66,62 @@ fi
 
 
 # ====== Linux QoS setup ====================================================
+success=1
 SYSTEM=`uname`
 if [ "$SYSTEM" = "Linux" ] ; then
-   echo "Linux"
    INTERFACES=`eval "ifconfig -a" 2>/dev/null | sed -ne 's|^\('$cur'[^[:space:][:punct:]]\{1,\}\).*$|\1|p'`
 
-   echo "=== Removing old configuration ... =============================="
    for iface in $INTERFACES ; do
-      tc qdisc del dev $iface root   # Ohne ID-Angabe wird Root mit jeder ID entfernt!
+      tc qdisc del dev $iface root 2>/dev/null   # Ohne ID-Angabe wird Root mit jeder ID entfernt!
    done
+
    if [ $addRule -eq 1 ] ; then
+      bandwidthParameter=""
+      weightParameter=""
+      delayParameter=""
+      lossParameter=""
+      errorParameter=""
       if [ "$BANDWIDTH" != "" ] ; then
-         BANDWIDTH="rate ${BANDWIDTH}kbit"
+         weightParameter=""
+         bandwidthParameter="rate ${BANDWIDTH}Kbit"
       fi
       if [ "$DELAY" != "" ] ; then
-         DELAY="delay ${DELAY}ms"
+         delayParameter="delay ${DELAY}ms"
       fi
       if [ "$LOSS" != "" ] ; then
-         LOSS="loss `./ldcalc ${LOSS} "*" "100.0"`%"
+         lossParameter="loss `./ldcalc ${LOSS} "*" "100.0"`%"
       fi
       if [ "$ERROR" != "" ] ; then
-         ERROR="corrupt `./ldcalc ${ERROR} "*" "100.0"`%"
+         errorParameter="corrupt `./ldcalc ${ERROR} "*" "100.0"`%"
       fi
+
       for iface in $INTERFACES ; do
-         echo "=== Configuring interface $iface ... ========================="
-         tc qdisc add dev $iface root handle 9$ID:0 prio
-         tc qdisc add dev $iface parent 9$ID:3 handle 8$ID:0 netem $DELAY $LOSS $ERROR
-         tc qdisc add dev $iface parent 8$ID:0 handle 7$ID:0 tbf $BANDWIDTH burst 16000 limit 150000
-         tc filter add dev $iface protocol ip parent 9$ID:0 prio 3 u32 match ip src $NETWORK_SRC match ip dst $NETWORK_DST flowid 9$ID:3
-         tc -s qdisc ls dev $iface
+         tc qdisc add dev $iface root handle 9$ID:0 cbq bandwidth 100Mbit avpkt 1000 cell 8 || success=0
+         tc class add dev $iface parent 9$ID:0 classid 9$ID:3 cbq \
+            bandwidth 100Mbit $bandwidthParameter $weightParameter \
+            prio 8 allot 1514 cell 8 maxburst 20 avpkt 1000 bounded || success=0
+         tc qdisc add dev $iface parent 9$ID:3 handle 8$ID:0 netem \
+            $delayParameter $lossParameter $errorParameter || success=0
+
+         tc filter add dev $iface protocol ip parent 9$ID:0 \
+            u32 match ip src $NETWORK_SRC match ip dst $NETWORK_DST flowid 9$ID:3 || success=0
+
+         if [ $bidirectionalQoS -eq 1 ] ; then
+            tc filter add dev $iface protocol ip parent 9$ID:0 \
+               u32 match ip src $NETWORK_DST match ip dst $NETWORK_SRC flowid 9$ID:3 || success=0
+         fi
+
+         # tc -s qdisc ls dev $iface || success=0
+         if [ $success -ne 1 ] ; then
+            echo >&2 "ERROR: Failed to configure QDiscs on interface $iface!"
+         fi
       done
    fi
 
 
 # ====== FreeBSD QoS setup ==================================================
 elif [ "$SYSTEM" = "FreeBSD" ] ; then
-   let ID2=$ID+1
+   ID2=$(($ID+1))
    /sbin/ipfw $ID  delete pipe $ID  2>/dev/null   # Delete old configuration
    /sbin/ipfw $ID2 delete pipe $ID2 2>/dev/null   # Delete old configuration
    if [ $addRule -eq 1 ] ; then
@@ -122,11 +142,11 @@ elif [ "$SYSTEM" = "FreeBSD" ] ; then
          fi
       fi
       queueParameters="queue 80 red 0.002/20/80/0.02"
-      /sbin/ipfw add $ID pipe $ID out src-ip $NETWORK_SRC dst-ip $NETWORK_DST
-      /sbin/ipfw pipe $ID config $BANDWIDTH $DELAY $LOSS $ERROR $queueParameters
+      /sbin/ipfw add $ID pipe $ID out src-ip $NETWORK_SRC dst-ip $NETWORK_DST || success=0
+      /sbin/ipfw pipe $ID config $BANDWIDTH $DELAY $LOSS $ERROR $queueParameters || success=0
       if [ $bidirectionalQoS -eq 1 ] ; then
-        /sbin/ipfw add $ID2 pipe $ID2 out src-ip $NETWORK_DST dst-ip $NETWORK_SRC
-        /sbin/ipfw pipe $ID2 config $BANDWIDTH $DELAY $LOSS $ERROR $queueParameters
+        /sbin/ipfw add $ID2 pipe $ID2 out src-ip $NETWORK_DST dst-ip $NETWORK_SRC || success=0
+        /sbin/ipfw pipe $ID2 config $BANDWIDTH $DELAY $LOSS $ERROR $queueParameters || success=0
       fi
    fi
 
@@ -134,5 +154,13 @@ elif [ "$SYSTEM" = "FreeBSD" ] ; then
 # ====== Other systems ======================================================
 else
    echo >&2 "ERROR: Unsupported system $SYSTEM!"
+   exit 1
+fi
+
+
+# ====== Check whether QoS configuration has been successful ================
+if [ $success -ne 1 ] ; then
+   echo >&2 "ERROR: setqos has failed to configure QoS settings!"
+   echo >&2 "Command on `hostname`: $0 $@"
    exit 1
 fi
