Improved helper scripts.

diff --git a/src/quic-setup/extract-pem b/src/quic-setup/extract-pem
--- a/src/quic-setup/extract-pem
+++ b/src/quic-setup/extract-pem
@@ -57,7 +57,32 @@ version () {
 # ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
-GETOPT="$(PATH=/usr/local/bin:${PATH} which getopt || true)"
+if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 4) )) ; then
+   echo "ERROR: Bash 4.4 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} is installed!"
+   exit 1
+fi
+UNAME="$(uname)"
+case "${UNAME}" in
+   FreeBSD)
+      GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt || true)"
+      ;;
+   NetBSD)
+      GETOPT="$(PATH="/usr/pkg/bin:${PATH}" command -v getopt || true)"
+      ;;
+   OpenBSD)
+      GETOPT="$(command -v gnugetopt || true)"
+      ;;
+   Darwin)
+      GETOPT="$(env PATH="/opt/homebrew/opt/gnu-getopt/bin:${PATH}" command -v getopt || true)"
+      ;;
+   *)
+      GETOPT="$(command -v getopt || true)"
+      ;;
+esac
+if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
+   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
+   exit 1
+fi
 options="$(${GETOPT} -o o:1flqhv --long output-prefix:,only-first-entry,skip-first-entry,skip-last-entry,quiet,help,version -a -- "$@")"
 # shellcheck disable=SC2181
 if [[ $? -ne 0 ]]; then
@@ -74,37 +99,37 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -o | --output-prefix)
          OUTPUT_PREFIX="$2"
-         shift 2
+         shift
          ;;
       -1 | --only-first-entry)
          ONLY_FIRST_ENTRY=1
-         shift
          ;;
       -f | --skip-first-entry)
          SKIP_FIRST_ENTRY=1
-         shift
          ;;
       -l | --skip-last-entry)
          SKIP_LAST_ENTRY=1
-         shift
          ;;
       -q | --quiet)
          QUIET=1
-         shift
          ;;
       -h | --help)
          usage 0
-         # shift
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
+      *)
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
+         exit 1
+         ;;
   esac
+  shift
 done
 if [ $# -lt 1 ] ; then
    usage 1
@@ -122,7 +147,6 @@ certificate=0
 csr=0
 crl=0
 key=0
-lastOutputFile=""
 while [ $# -gt 0 ] ; do
    PEM_FILE="$1"
    shift
@@ -135,6 +159,8 @@ while [ $# -gt 0 ] ; do
    if [ ${QUIET} -eq 0 ] ; then
       echo -e "\e[34m$(eval_gettext "Extracting \${PEM_FILE} ...")\e[0m"
    fi
+
+   lastOutputFile=""
    outputFile=""
    entry=0
    while read -r line ; do
@@ -157,7 +183,7 @@ while [ $# -gt 0 ] ; do
                outputFile="${OUTPUT_PREFIX}${crl}.crl"
             elif [ "${type}" == "PRIVATE KEY" ] || \
                  [ "${type}" == "ENCRYPTED PRIVATE KEY" ] ; then
-               key=$((crl + 1))
+               key=$((key + 1))
                outputFile="${OUTPUT_PREFIX}${key}.key"
                touch "${outputFile}"
                chmod 600 "${outputFile}"
@@ -180,7 +206,7 @@ while [ $# -gt 0 ] ; do
             lastOutputFile="${outputFile}"
             if [ ${entry} -eq 1 ] ; then
                if [ ${ONLY_FIRST_ENTRY} -eq 1 ] ; then
-                  continue
+                  break
                elif [ ${SKIP_FIRST_ENTRY} -eq 1 ] ; then
                   rm "${lastOutputFile}"
                   if [ ${QUIET} -eq 0 ] ; then
@@ -195,19 +221,20 @@ while [ $# -gt 0 ] ; do
          fi
       fi
    done <"${PEM_FILE}"
-done
-if [ "${lastOutputFile}" != "" ] ; then
-   if [ ${SKIP_LAST_ENTRY} -eq 1 ] ; then
-      rm "${lastOutputFile}"
-      if [ ${QUIET} -eq 0 ] ; then
-         echo "=> $(gettext "SKIPPING") ${lastOutputFile}"
-      fi
-   else
-      if [ ${QUIET} -eq 0 ] ; then
-         echo "=> ${lastOutputFile}"
+   if [ "${lastOutputFile}" != "" ] ; then
+      if [ ${SKIP_LAST_ENTRY} -eq 1 ] ; then
+         rm "${lastOutputFile}"
+         if [ ${QUIET} -eq 0 ] ; then
+            echo "=> $(gettext "SKIPPING") ${lastOutputFile}"
+         fi
+      else
+         if [ ${QUIET} -eq 0 ] ; then
+            echo "=> ${lastOutputFile}"
+         fi
       fi
    fi
-fi
+done
+
 if [ ${QUIET} -eq 0 ] ; then
    echo -e "\e[34m$(eval_gettext "Done: \${certificate} certificates, \${csr} CSRs, \${crl} CRLs, \${key} keys")\e[0m"
 fi
diff --git a/src/quic-setup/make-test-certificates b/src/quic-setup/make-test-certificates
--- a/src/quic-setup/make-test-certificates
+++ b/src/quic-setup/make-test-certificates
@@ -33,9 +33,19 @@ set -euo pipefail
 
 
 DIRNAME="$(dirname "$0")"
+HOSTNAME="$(hostname -f 2>/dev/null || hostname 2>/dev/null || echo "localhost")"
+if [ "${#HOSTNAME}" -gt 64 ] ; then
+   echo >&2 "ERROR: The FQDN hostname ${HOSTNAME} is too long (> 64 bytes) for a CN!"
+   exit 1
+fi
+UNAME="$(uname)"
+if [ "${UNAME}" == "Darwin" ] ; then
+   PATH="/opt/homebrew/opt/openssl/bin:$PATH"
+fi
+
 
 # Generate a client certificate for the local machine (hostname as FQDN):
-"${DIRNAME}/generate-test-certificates" TestCA --client --san LOCAL "$(hostname -f)"
+"${DIRNAME}/generate-test-certificates" TestCA --client --san LOCAL "${HOSTNAME}"
 
 # Generate some test server certificates:
 # NOTE: These lines must contain resolvable (/etc/hosts or DNS) hostnames:
@@ -46,7 +56,7 @@ DIRNAME="$(dirname "$0")"
 # Generate some test server certificates:
 "${DIRNAME}/generate-test-certificates" TestCA --server sognsvann.company.example
 "${DIRNAME}/generate-test-certificates" TestCA --server svartkulp.company.example
-"${DIRNAME}/generate-test-certificates" TestCA --server svartkulp.company.example
+"${DIRNAME}/generate-test-certificates" TestCA --server maridalsvannet.company.example
 "${DIRNAME}/generate-test-certificates" TestCA --server blanksjoe.company.example
 "${DIRNAME}/generate-test-certificates" TestCA --server tryvann.company.example
 "${DIRNAME}/generate-test-certificates" TestCA --server aaklungen.company.example
